using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace Lang.Php
{
    public enum Timezones
    {
        // Africa
        [RenderValue("'Africa/Abidjan'")]
        Africa_Abidjan,
        [RenderValue("'Africa/Accra'")]
        Africa_Accra,
        [RenderValue("'Africa/Addis_Ababa'")]
        Africa_Addis_Ababa,
        [RenderValue("'Africa/Algiers'")]
        Africa_Algiers,
        [RenderValue("'Africa/Asmara'")]
        Africa_Asmara,
        [RenderValue("'Africa/Asmera'")]
        Africa_Asmera,
        [RenderValue("'Africa/Bamako'")]
        Africa_Bamako,
        [RenderValue("'Africa/Bangui'")]
        Africa_Bangui,
        [RenderValue("'Africa/Banjul'")]
        Africa_Banjul,
        [RenderValue("'Africa/Bissau'")]
        Africa_Bissau,
        [RenderValue("'Africa/Blantyre'")]
        Africa_Blantyre,
        [RenderValue("'Africa/Brazzaville'")]
        Africa_Brazzaville,
        [RenderValue("'Africa/Bujumbura'")]
        Africa_Bujumbura,
        [RenderValue("'Africa/Cairo'")]
        Africa_Cairo,
        [RenderValue("'Africa/Casablanca'")]
        Africa_Casablanca,
        [RenderValue("'Africa/Ceuta'")]
        Africa_Ceuta,
        [RenderValue("'Africa/Conakry'")]
        Africa_Conakry,
        [RenderValue("'Africa/Dakar'")]
        Africa_Dakar,
        [RenderValue("'Africa/Dar_es_Salaam'")]
        Africa_Dar_es_Salaam,
        [RenderValue("'Africa/Djibouti'")]
        Africa_Djibouti,
        [RenderValue("'Africa/Douala'")]
        Africa_Douala,
        [RenderValue("'Africa/El_Aaiun'")]
        Africa_El_Aaiun,
        [RenderValue("'Africa/Freetown'")]
        Africa_Freetown,
        [RenderValue("'Africa/Gaborone'")]
        Africa_Gaborone,
        [RenderValue("'Africa/Harare'")]
        Africa_Harare,
        [RenderValue("'Africa/Johannesburg'")]
        Africa_Johannesburg,
        [RenderValue("'Africa/Juba'")]
        Africa_Juba,
        [RenderValue("'Africa/Kampala'")]
        Africa_Kampala,
        [RenderValue("'Africa/Khartoum'")]
        Africa_Khartoum,
        [RenderValue("'Africa/Kigali'")]
        Africa_Kigali,
        [RenderValue("'Africa/Kinshasa'")]
        Africa_Kinshasa,
        [RenderValue("'Africa/Lagos'")]
        Africa_Lagos,
        [RenderValue("'Africa/Libreville'")]
        Africa_Libreville,
        [RenderValue("'Africa/Lome'")]
        Africa_Lome,
        [RenderValue("'Africa/Luanda'")]
        Africa_Luanda,
        [RenderValue("'Africa/Lubumbashi'")]
        Africa_Lubumbashi,
        [RenderValue("'Africa/Lusaka'")]
        Africa_Lusaka,
        [RenderValue("'Africa/Malabo'")]
        Africa_Malabo,
        [RenderValue("'Africa/Maputo'")]
        Africa_Maputo,
        [RenderValue("'Africa/Maseru'")]
        Africa_Maseru,
        [RenderValue("'Africa/Mbabane'")]
        Africa_Mbabane,
        [RenderValue("'Africa/Mogadishu'")]
        Africa_Mogadishu,
        [RenderValue("'Africa/Monrovia'")]
        Africa_Monrovia,
        [RenderValue("'Africa/Nairobi'")]
        Africa_Nairobi,
        [RenderValue("'Africa/Ndjamena'")]
        Africa_Ndjamena,
        [RenderValue("'Africa/Niamey'")]
        Africa_Niamey,
        [RenderValue("'Africa/Nouakchott'")]
        Africa_Nouakchott,
        [RenderValue("'Africa/Ouagadougou'")]
        Africa_Ouagadougou,
        [RenderValue("'Africa/Porto-Novo'")]
        Africa_Porto_Novo,
        [RenderValue("'Africa/Sao_Tome'")]
        Africa_Sao_Tome,
        [RenderValue("'Africa/Timbuktu'")]
        Africa_Timbuktu,
        [RenderValue("'Africa/Tripoli'")]
        Africa_Tripoli,
        [RenderValue("'Africa/Tunis'")]
        Africa_Tunis,
        [RenderValue("'Africa/Windhoek'")]
        Africa_Windhoek,

        // America
        [RenderValue("'America/Adak'")]
        America_Adak,
        [RenderValue("'America/Anchorage'")]
        America_Anchorage,
        [RenderValue("'America/Anguilla'")]
        America_Anguilla,
        [RenderValue("'America/Antigua'")]
        America_Antigua,
        [RenderValue("'America/Araguaina'")]
        America_Araguaina,
        [RenderValue("'America/Argentina/Buenos_Aires'")]
        America_Argentina_Buenos_Aires,
        [RenderValue("'America/Argentina/Catamarca'")]
        America_Argentina_Catamarca,
        [RenderValue("'America/Argentina/ComodRivadavia'")]
        America_Argentina_ComodRivadavia,
        [RenderValue("'America/Argentina/Cordoba'")]
        America_Argentina_Cordoba,
        [RenderValue("'America/Argentina/Jujuy'")]
        America_Argentina_Jujuy,
        [RenderValue("'America/Argentina/La_Rioja'")]
        America_Argentina_La_Rioja,
        [RenderValue("'America/Argentina/Mendoza'")]
        America_Argentina_Mendoza,
        [RenderValue("'America/Argentina/Rio_Gallegos'")]
        America_Argentina_Rio_Gallegos,
        [RenderValue("'America/Argentina/Salta'")]
        America_Argentina_Salta,
        [RenderValue("'America/Argentina/San_Juan'")]
        America_Argentina_San_Juan,
        [RenderValue("'America/Argentina/San_Luis'")]
        America_Argentina_San_Luis,
        [RenderValue("'America/Argentina/Tucuman'")]
        America_Argentina_Tucuman,
        [RenderValue("'America/Argentina/Ushuaia'")]
        America_Argentina_Ushuaia,
        [RenderValue("'America/Aruba'")]
        America_Aruba,
        [RenderValue("'America/Asuncion'")]
        America_Asuncion,
        [RenderValue("'America/Atikokan'")]
        America_Atikokan,
        [RenderValue("'America/Atka'")]
        America_Atka,
        [RenderValue("'America/Bahia'")]
        America_Bahia,
        [RenderValue("'America/Bahia_Banderas'")]
        America_Bahia_Banderas,
        [RenderValue("'America/Barbados'")]
        America_Barbados,
        [RenderValue("'America/Belem'")]
        America_Belem,
        [RenderValue("'America/Belize'")]
        America_Belize,
        [RenderValue("'America/Blanc-Sablon'")]
        America_Blanc_Sablon,
        [RenderValue("'America/Boa_Vista'")]
        America_Boa_Vista,
        [RenderValue("'America/Bogota'")]
        America_Bogota,
        [RenderValue("'America/Boise'")]
        America_Boise,
        [RenderValue("'America/Buenos_Aires'")]
        America_Buenos_Aires,
        [RenderValue("'America/Cambridge_Bay'")]
        America_Cambridge_Bay,
        [RenderValue("'America/Campo_Grande'")]
        America_Campo_Grande,
        [RenderValue("'America/Cancun'")]
        America_Cancun,
        [RenderValue("'America/Caracas'")]
        America_Caracas,
        [RenderValue("'America/Catamarca'")]
        America_Catamarca,
        [RenderValue("'America/Cayenne'")]
        America_Cayenne,
        [RenderValue("'America/Cayman'")]
        America_Cayman,
        [RenderValue("'America/Chicago'")]
        America_Chicago,
        [RenderValue("'America/Chihuahua'")]
        America_Chihuahua,
        [RenderValue("'America/Coral_Harbour'")]
        America_Coral_Harbour,
        [RenderValue("'America/Cordoba'")]
        America_Cordoba,
        [RenderValue("'America/Costa_Rica'")]
        America_Costa_Rica,
        [RenderValue("'America/Creston'")]
        America_Creston,
        [RenderValue("'America/Cuiaba'")]
        America_Cuiaba,
        [RenderValue("'America/Curacao'")]
        America_Curacao,
        [RenderValue("'America/Danmarkshavn'")]
        America_Danmarkshavn,
        [RenderValue("'America/Dawson'")]
        America_Dawson,
        [RenderValue("'America/Dawson_Creek'")]
        America_Dawson_Creek,
        [RenderValue("'America/Denver'")]
        America_Denver,
        [RenderValue("'America/Detroit'")]
        America_Detroit,
        [RenderValue("'America/Dominica'")]
        America_Dominica,
        [RenderValue("'America/Edmonton'")]
        America_Edmonton,
        [RenderValue("'America/Eirunepe'")]
        America_Eirunepe,
        [RenderValue("'America/El_Salvador'")]
        America_El_Salvador,
        [RenderValue("'America/Ensenada'")]
        America_Ensenada,
        [RenderValue("'America/Fort_Wayne'")]
        America_Fort_Wayne,
        [RenderValue("'America/Fortaleza'")]
        America_Fortaleza,
        [RenderValue("'America/Glace_Bay'")]
        America_Glace_Bay,
        [RenderValue("'America/Godthab'")]
        America_Godthab,
        [RenderValue("'America/Goose_Bay'")]
        America_Goose_Bay,
        [RenderValue("'America/Grand_Turk'")]
        America_Grand_Turk,
        [RenderValue("'America/Grenada'")]
        America_Grenada,
        [RenderValue("'America/Guadeloupe'")]
        America_Guadeloupe,
        [RenderValue("'America/Guatemala'")]
        America_Guatemala,
        [RenderValue("'America/Guayaquil'")]
        America_Guayaquil,
        [RenderValue("'America/Guyana'")]
        America_Guyana,
        [RenderValue("'America/Halifax'")]
        America_Halifax,
        [RenderValue("'America/Havana'")]
        America_Havana,
        [RenderValue("'America/Hermosillo'")]
        America_Hermosillo,
        [RenderValue("'America/Indiana/Indianapolis'")]
        America_Indiana_Indianapolis,
        [RenderValue("'America/Indiana/Knox'")]
        America_Indiana_Knox,
        [RenderValue("'America/Indiana/Marengo'")]
        America_Indiana_Marengo,
        [RenderValue("'America/Indiana/Petersburg'")]
        America_Indiana_Petersburg,
        [RenderValue("'America/Indiana/Tell_City'")]
        America_Indiana_Tell_City,
        [RenderValue("'America/Indiana/Vevay'")]
        America_Indiana_Vevay,
        [RenderValue("'America/Indiana/Vincennes'")]
        America_Indiana_Vincennes,
        [RenderValue("'America/Indiana/Winamac'")]
        America_Indiana_Winamac,
        [RenderValue("'America/Indianapolis'")]
        America_Indianapolis,
        [RenderValue("'America/Inuvik'")]
        America_Inuvik,
        [RenderValue("'America/Iqaluit'")]
        America_Iqaluit,
        [RenderValue("'America/Jamaica'")]
        America_Jamaica,
        [RenderValue("'America/Jujuy'")]
        America_Jujuy,
        [RenderValue("'America/Juneau'")]
        America_Juneau,
        [RenderValue("'America/Kentucky/Louisville'")]
        America_Kentucky_Louisville,
        [RenderValue("'America/Kentucky/Monticello'")]
        America_Kentucky_Monticello,
        [RenderValue("'America/Knox_IN'")]
        America_Knox_IN,
        [RenderValue("'America/Kralendijk'")]
        America_Kralendijk,
        [RenderValue("'America/La_Paz'")]
        America_La_Paz,
        [RenderValue("'America/Lima'")]
        America_Lima,
        [RenderValue("'America/Los_Angeles'")]
        America_Los_Angeles,
        [RenderValue("'America/Louisville'")]
        America_Louisville,
        [RenderValue("'America/Lower_Princes'")]
        America_Lower_Princes,
        [RenderValue("'America/Maceio'")]
        America_Maceio,
        [RenderValue("'America/Managua'")]
        America_Managua,
        [RenderValue("'America/Manaus'")]
        America_Manaus,
        [RenderValue("'America/Marigot'")]
        America_Marigot,
        [RenderValue("'America/Martinique'")]
        America_Martinique,
        [RenderValue("'America/Matamoros'")]
        America_Matamoros,
        [RenderValue("'America/Mazatlan'")]
        America_Mazatlan,
        [RenderValue("'America/Mendoza'")]
        America_Mendoza,
        [RenderValue("'America/Menominee'")]
        America_Menominee,
        [RenderValue("'America/Merida'")]
        America_Merida,
        [RenderValue("'America/Metlakatla'")]
        America_Metlakatla,
        [RenderValue("'America/Mexico_City'")]
        America_Mexico_City,
        [RenderValue("'America/Miquelon'")]
        America_Miquelon,
        [RenderValue("'America/Moncton'")]
        America_Moncton,
        [RenderValue("'America/Monterrey'")]
        America_Monterrey,
        [RenderValue("'America/Montevideo'")]
        America_Montevideo,
        [RenderValue("'America/Montreal'")]
        America_Montreal,
        [RenderValue("'America/Montserrat'")]
        America_Montserrat,
        [RenderValue("'America/Nassau'")]
        America_Nassau,
        [RenderValue("'America/New_York'")]
        America_New_York,
        [RenderValue("'America/Nipigon'")]
        America_Nipigon,
        [RenderValue("'America/Nome'")]
        America_Nome,
        [RenderValue("'America/Noronha'")]
        America_Noronha,
        [RenderValue("'America/North_Dakota/Beulah'")]
        America_North_Dakota_Beulah,
        [RenderValue("'America/North_Dakota/Center'")]
        America_North_Dakota_Center,
        [RenderValue("'America/North_Dakota/New_Salem'")]
        America_North_Dakota_New_Salem,
        [RenderValue("'America/Ojinaga'")]
        America_Ojinaga,
        [RenderValue("'America/Panama'")]
        America_Panama,
        [RenderValue("'America/Pangnirtung'")]
        America_Pangnirtung,
        [RenderValue("'America/Paramaribo'")]
        America_Paramaribo,
        [RenderValue("'America/Phoenix'")]
        America_Phoenix,
        [RenderValue("'America/Port-au-Prince'")]
        America_Port_au_Prince,
        [RenderValue("'America/Port_of_Spain'")]
        America_Port_of_Spain,
        [RenderValue("'America/Porto_Acre'")]
        America_Porto_Acre,
        [RenderValue("'America/Porto_Velho'")]
        America_Porto_Velho,
        [RenderValue("'America/Puerto_Rico'")]
        America_Puerto_Rico,
        [RenderValue("'America/Rainy_River'")]
        America_Rainy_River,
        [RenderValue("'America/Rankin_Inlet'")]
        America_Rankin_Inlet,
        [RenderValue("'America/Recife'")]
        America_Recife,
        [RenderValue("'America/Regina'")]
        America_Regina,
        [RenderValue("'America/Resolute'")]
        America_Resolute,
        [RenderValue("'America/Rio_Branco'")]
        America_Rio_Branco,
        [RenderValue("'America/Rosario'")]
        America_Rosario,
        [RenderValue("'America/Santa_Isabel'")]
        America_Santa_Isabel,
        [RenderValue("'America/Santarem'")]
        America_Santarem,
        [RenderValue("'America/Santiago'")]
        America_Santiago,
        [RenderValue("'America/Santo_Domingo'")]
        America_Santo_Domingo,
        [RenderValue("'America/Sao_Paulo'")]
        America_Sao_Paulo,
        [RenderValue("'America/Scoresbysund'")]
        America_Scoresbysund,
        [RenderValue("'America/Shiprock'")]
        America_Shiprock,
        [RenderValue("'America/Sitka'")]
        America_Sitka,
        [RenderValue("'America/St_Barthelemy'")]
        America_St_Barthelemy,
        [RenderValue("'America/St_Johns'")]
        America_St_Johns,
        [RenderValue("'America/St_Kitts'")]
        America_St_Kitts,
        [RenderValue("'America/St_Lucia'")]
        America_St_Lucia,
        [RenderValue("'America/St_Thomas'")]
        America_St_Thomas,
        [RenderValue("'America/St_Vincent'")]
        America_St_Vincent,
        [RenderValue("'America/Swift_Current'")]
        America_Swift_Current,
        [RenderValue("'America/Tegucigalpa'")]
        America_Tegucigalpa,
        [RenderValue("'America/Thule'")]
        America_Thule,
        [RenderValue("'America/Thunder_Bay'")]
        America_Thunder_Bay,
        [RenderValue("'America/Tijuana'")]
        America_Tijuana,
        [RenderValue("'America/Toronto'")]
        America_Toronto,
        [RenderValue("'America/Tortola'")]
        America_Tortola,
        [RenderValue("'America/Vancouver'")]
        America_Vancouver,
        [RenderValue("'America/Virgin'")]
        America_Virgin,
        [RenderValue("'America/Whitehorse'")]
        America_Whitehorse,
        [RenderValue("'America/Winnipeg'")]
        America_Winnipeg,
        [RenderValue("'America/Yakutat'")]
        America_Yakutat,
        [RenderValue("'America/Yellowknife'")]
        America_Yellowknife,

        // Antarctica
        [RenderValue("'Antarctica/Casey'")]
        Antarctica_Casey,
        [RenderValue("'Antarctica/Davis'")]
        Antarctica_Davis,
        [RenderValue("'Antarctica/DumontDUrville'")]
        Antarctica_DumontDUrville,
        [RenderValue("'Antarctica/Macquarie'")]
        Antarctica_Macquarie,
        [RenderValue("'Antarctica/Mawson'")]
        Antarctica_Mawson,
        [RenderValue("'Antarctica/McMurdo'")]
        Antarctica_McMurdo,
        [RenderValue("'Antarctica/Palmer'")]
        Antarctica_Palmer,
        [RenderValue("'Antarctica/Rothera'")]
        Antarctica_Rothera,
        [RenderValue("'Antarctica/South_Pole'")]
        Antarctica_South_Pole,
        [RenderValue("'Antarctica/Syowa'")]
        Antarctica_Syowa,
        [RenderValue("'Antarctica/Vostok'")]
        Antarctica_Vostok,


        // Arctic 
        [RenderValue("'Arctic/Longyearbyen'")]
        Arctic_Longyearbyen,

        // Asia
        [RenderValue("'Asia/Aden'")]
        Asia_Aden,
        [RenderValue("'Asia/Almaty'")]
        Asia_Almaty,
        [RenderValue("'Asia/Amman'")]
        Asia_Amman,
        [RenderValue("'Asia/Anadyr'")]
        Asia_Anadyr,
        [RenderValue("'Asia/Aqtau'")]
        Asia_Aqtau,
        [RenderValue("'Asia/Aqtobe'")]
        Asia_Aqtobe,
        [RenderValue("'Asia/Ashgabat'")]
        Asia_Ashgabat,
        [RenderValue("'Asia/Ashkhabad'")]
        Asia_Ashkhabad,
        [RenderValue("'Asia/Baghdad'")]
        Asia_Baghdad,
        [RenderValue("'Asia/Bahrain'")]
        Asia_Bahrain,
        [RenderValue("'Asia/Baku'")]
        Asia_Baku,
        [RenderValue("'Asia/Bangkok'")]
        Asia_Bangkok,
        [RenderValue("'Asia/Beirut'")]
        Asia_Beirut,
        [RenderValue("'Asia/Bishkek'")]
        Asia_Bishkek,
        [RenderValue("'Asia/Brunei'")]
        Asia_Brunei,
        [RenderValue("'Asia/Calcutta'")]
        Asia_Calcutta,
        [RenderValue("'Asia/Choibalsan'")]
        Asia_Choibalsan,
        [RenderValue("'Asia/Chongqing'")]
        Asia_Chongqing,
        [RenderValue("'Asia/Chungking'")]
        Asia_Chungking,
        [RenderValue("'Asia/Colombo'")]
        Asia_Colombo,
        [RenderValue("'Asia/Dacca'")]
        Asia_Dacca,
        [RenderValue("'Asia/Damascus'")]
        Asia_Damascus,
        [RenderValue("'Asia/Dhaka'")]
        Asia_Dhaka,
        [RenderValue("'Asia/Dili'")]
        Asia_Dili,
        [RenderValue("'Asia/Dubai'")]
        Asia_Dubai,
        [RenderValue("'Asia/Dushanbe'")]
        Asia_Dushanbe,
        [RenderValue("'Asia/Gaza'")]
        Asia_Gaza,
        [RenderValue("'Asia/Harbin'")]
        Asia_Harbin,
        [RenderValue("'Asia/Hebron'")]
        Asia_Hebron,
        [RenderValue("'Asia/Ho_Chi_Minh'")]
        Asia_Ho_Chi_Minh,
        [RenderValue("'Asia/Hong_Kong'")]
        Asia_Hong_Kong,
        [RenderValue("'Asia/Hovd'")]
        Asia_Hovd,
        [RenderValue("'Asia/Irkutsk'")]
        Asia_Irkutsk,
        [RenderValue("'Asia/Istanbul'")]
        Asia_Istanbul,
        [RenderValue("'Asia/Jakarta'")]
        Asia_Jakarta,
        [RenderValue("'Asia/Jayapura'")]
        Asia_Jayapura,
        [RenderValue("'Asia/Jerusalem'")]
        Asia_Jerusalem,
        [RenderValue("'Asia/Kabul'")]
        Asia_Kabul,
        [RenderValue("'Asia/Kamchatka'")]
        Asia_Kamchatka,
        [RenderValue("'Asia/Karachi'")]
        Asia_Karachi,
        [RenderValue("'Asia/Kashgar'")]
        Asia_Kashgar,
        [RenderValue("'Asia/Kathmandu'")]
        Asia_Kathmandu,
        [RenderValue("'Asia/Katmandu'")]
        Asia_Katmandu,
        [RenderValue("'Asia/Khandyga'")]
        Asia_Khandyga,
        [RenderValue("'Asia/Kolkata'")]
        Asia_Kolkata,
        [RenderValue("'Asia/Krasnoyarsk'")]
        Asia_Krasnoyarsk,
        [RenderValue("'Asia/Kuala_Lumpur'")]
        Asia_Kuala_Lumpur,
        [RenderValue("'Asia/Kuching'")]
        Asia_Kuching,
        [RenderValue("'Asia/Kuwait'")]
        Asia_Kuwait,
        [RenderValue("'Asia/Macao'")]
        Asia_Macao,
        [RenderValue("'Asia/Macau'")]
        Asia_Macau,
        [RenderValue("'Asia/Magadan'")]
        Asia_Magadan,
        [RenderValue("'Asia/Makassar'")]
        Asia_Makassar,
        [RenderValue("'Asia/Manila'")]
        Asia_Manila,
        [RenderValue("'Asia/Muscat'")]
        Asia_Muscat,
        [RenderValue("'Asia/Nicosia'")]
        Asia_Nicosia,
        [RenderValue("'Asia/Novokuznetsk'")]
        Asia_Novokuznetsk,
        [RenderValue("'Asia/Novosibirsk'")]
        Asia_Novosibirsk,
        [RenderValue("'Asia/Omsk'")]
        Asia_Omsk,
        [RenderValue("'Asia/Oral'")]
        Asia_Oral,
        [RenderValue("'Asia/Phnom_Penh'")]
        Asia_Phnom_Penh,
        [RenderValue("'Asia/Pontianak'")]
        Asia_Pontianak,
        [RenderValue("'Asia/Pyongyang'")]
        Asia_Pyongyang,
        [RenderValue("'Asia/Qatar'")]
        Asia_Qatar,
        [RenderValue("'Asia/Qyzylorda'")]
        Asia_Qyzylorda,
        [RenderValue("'Asia/Rangoon'")]
        Asia_Rangoon,
        [RenderValue("'Asia/Riyadh'")]
        Asia_Riyadh,
        [RenderValue("'Asia/Saigon'")]
        Asia_Saigon,
        [RenderValue("'Asia/Sakhalin'")]
        Asia_Sakhalin,
        [RenderValue("'Asia/Samarkand'")]
        Asia_Samarkand,
        [RenderValue("'Asia/Seoul'")]
        Asia_Seoul,
        [RenderValue("'Asia/Shanghai'")]
        Asia_Shanghai,
        [RenderValue("'Asia/Singapore'")]
        Asia_Singapore,
        [RenderValue("'Asia/Taipei'")]
        Asia_Taipei,
        [RenderValue("'Asia/Tashkent'")]
        Asia_Tashkent,
        [RenderValue("'Asia/Tbilisi'")]
        Asia_Tbilisi,
        [RenderValue("'Asia/Tehran'")]
        Asia_Tehran,
        [RenderValue("'Asia/Tel_Aviv'")]
        Asia_Tel_Aviv,
        [RenderValue("'Asia/Thimbu'")]
        Asia_Thimbu,
        [RenderValue("'Asia/Thimphu'")]
        Asia_Thimphu,
        [RenderValue("'Asia/Tokyo'")]
        Asia_Tokyo,
        [RenderValue("'Asia/Ujung_Pandang'")]
        Asia_Ujung_Pandang,
        [RenderValue("'Asia/Ulaanbaatar'")]
        Asia_Ulaanbaatar,
        [RenderValue("'Asia/Ulan_Bator'")]
        Asia_Ulan_Bator,
        [RenderValue("'Asia/Urumqi'")]
        Asia_Urumqi,
        [RenderValue("'Asia/Ust-Nera'")]
        Asia_Ust_Nera,
        [RenderValue("'Asia/Vientiane'")]
        Asia_Vientiane,
        [RenderValue("'Asia/Vladivostok'")]
        Asia_Vladivostok,
        [RenderValue("'Asia/Yakutsk'")]
        Asia_Yakutsk,
        [RenderValue("'Asia/Yekaterinburg'")]
        Asia_Yekaterinburg,
        [RenderValue("'Asia/Yerevan'")]
        Asia_Yerevan,

        // Atlantic
        [RenderValue("'Atlantic/Azores'")]
        Atlantic_Azores,
        [RenderValue("'Atlantic/Bermuda'")]
        Atlantic_Bermuda,
        [RenderValue("'Atlantic/Canary'")]
        Atlantic_Canary,
        [RenderValue("'Atlantic/Cape_Verde'")]
        Atlantic_Cape_Verde,
        [RenderValue("'Atlantic/Faeroe'")]
        Atlantic_Faeroe,
        [RenderValue("'Atlantic/Faroe'")]
        Atlantic_Faroe,
        [RenderValue("'Atlantic/Jan_Mayen'")]
        Atlantic_Jan_Mayen,
        [RenderValue("'Atlantic/Madeira'")]
        Atlantic_Madeira,
        [RenderValue("'Atlantic/Reykjavik'")]
        Atlantic_Reykjavik,
        [RenderValue("'Atlantic/South_Georgia'")]
        Atlantic_South_Georgia,
        [RenderValue("'Atlantic/St_Helena'")]
        Atlantic_St_Helena,
        [RenderValue("'Atlantic/Stanley'")]
        Atlantic_Stanley,


        // Australia
        [RenderValue("'Australia/ACT'")]
        Australia_ACT,
        [RenderValue("'Australia/Adelaide'")]
        Australia_Adelaide,
        [RenderValue("'Australia/Brisbane'")]
        Australia_Brisbane,
        [RenderValue("'Australia/Broken_Hill'")]
        Australia_Broken_Hill,
        [RenderValue("'Australia/Canberra'")]
        Australia_Canberra,
        [RenderValue("'Australia/Currie'")]
        Australia_Currie,
        [RenderValue("'Australia/Darwin'")]
        Australia_Darwin,
        [RenderValue("'Australia/Eucla'")]
        Australia_Eucla,
        [RenderValue("'Australia/Hobart'")]
        Australia_Hobart,
        [RenderValue("'Australia/LHI'")]
        Australia_LHI,
        [RenderValue("'Australia/Lindeman'")]
        Australia_Lindeman,
        [RenderValue("'Australia/Lord_Howe'")]
        Australia_Lord_Howe,
        [RenderValue("'Australia/Melbourne'")]
        Australia_Melbourne,
        [RenderValue("'Australia/North'")]
        Australia_North,
        [RenderValue("'Australia/NSW'")]
        Australia_NSW,
        [RenderValue("'Australia/Perth'")]
        Australia_Perth,
        [RenderValue("'Australia/Queensland'")]
        Australia_Queensland,
        [RenderValue("'Australia/South'")]
        Australia_South,
        [RenderValue("'Australia/Sydney'")]
        Australia_Sydney,
        [RenderValue("'Australia/Tasmania'")]
        Australia_Tasmania,
        [RenderValue("'Australia/Victoria'")]
        Australia_Victoria,
        [RenderValue("'Australia/West'")]
        Australia_West,
        [RenderValue("'Australia/Yancowinna'")]
        Australia_Yancowinna,

        // Europe
        [RenderValue("'Europe/Amsterdam'")]
        Europe_Amsterdam,
        [RenderValue("'Europe/Andorra'")]
        Europe_Andorra,
        [RenderValue("'Europe/Athens'")]
        Europe_Athens,
        [RenderValue("'Europe/Belfast'")]
        Europe_Belfast,
        [RenderValue("'Europe/Belgrade'")]
        Europe_Belgrade,
        [RenderValue("'Europe/Berlin'")]
        Europe_Berlin,
        [RenderValue("'Europe/Bratislava'")]
        Europe_Bratislava,
        [RenderValue("'Europe/Brussels'")]
        Europe_Brussels,
        [RenderValue("'Europe/Bucharest'")]
        Europe_Bucharest,
        [RenderValue("'Europe/Budapest'")]
        Europe_Budapest,
        [RenderValue("'Europe/Busingen'")]
        Europe_Busingen,
        [RenderValue("'Europe/Chisinau'")]
        Europe_Chisinau,
        [RenderValue("'Europe/Copenhagen'")]
        Europe_Copenhagen,
        [RenderValue("'Europe/Dublin'")]
        Europe_Dublin,
        [RenderValue("'Europe/Gibraltar'")]
        Europe_Gibraltar,
        [RenderValue("'Europe/Guernsey'")]
        Europe_Guernsey,
        [RenderValue("'Europe/Helsinki'")]
        Europe_Helsinki,
        [RenderValue("'Europe/Isle_of_Man'")]
        Europe_Isle_of_Man,
        [RenderValue("'Europe/Istanbul'")]
        Europe_Istanbul,
        [RenderValue("'Europe/Jersey'")]
        Europe_Jersey,
        [RenderValue("'Europe/Kaliningrad'")]
        Europe_Kaliningrad,
        [RenderValue("'Europe/Kiev'")]
        Europe_Kiev,
        [RenderValue("'Europe/Lisbon'")]
        Europe_Lisbon,
        [RenderValue("'Europe/Ljubljana'")]
        Europe_Ljubljana,
        [RenderValue("'Europe/London'")]
        Europe_London,
        [RenderValue("'Europe/Luxembourg'")]
        Europe_Luxembourg,
        [RenderValue("'Europe/Madrid'")]
        Europe_Madrid,
        [RenderValue("'Europe/Malta'")]
        Europe_Malta,
        [RenderValue("'Europe/Mariehamn'")]
        Europe_Mariehamn,
        [RenderValue("'Europe/Minsk'")]
        Europe_Minsk,
        [RenderValue("'Europe/Monaco'")]
        Europe_Monaco,
        [RenderValue("'Europe/Moscow'")]
        Europe_Moscow,
        [RenderValue("'Europe/Nicosia'")]
        Europe_Nicosia,
        [RenderValue("'Europe/Oslo'")]
        Europe_Oslo,
        [RenderValue("'Europe/Paris'")]
        Europe_Paris,
        [RenderValue("'Europe/Podgorica'")]
        Europe_Podgorica,
        [RenderValue("'Europe/Prague'")]
        Europe_Prague,
        [RenderValue("'Europe/Riga'")]
        Europe_Riga,
        [RenderValue("'Europe/Rome'")]
        Europe_Rome,
        [RenderValue("'Europe/Samara'")]
        Europe_Samara,
        [RenderValue("'Europe/San_Marino'")]
        Europe_San_Marino,
        [RenderValue("'Europe/Sarajevo'")]
        Europe_Sarajevo,
        [RenderValue("'Europe/Simferopol'")]
        Europe_Simferopol,
        [RenderValue("'Europe/Skopje'")]
        Europe_Skopje,
        [RenderValue("'Europe/Sofia'")]
        Europe_Sofia,
        [RenderValue("'Europe/Stockholm'")]
        Europe_Stockholm,
        [RenderValue("'Europe/Tallinn'")]
        Europe_Tallinn,
        [RenderValue("'Europe/Tirane'")]
        Europe_Tirane,
        [RenderValue("'Europe/Tiraspol'")]
        Europe_Tiraspol,
        [RenderValue("'Europe/Uzhgorod'")]
        Europe_Uzhgorod,
        [RenderValue("'Europe/Vaduz'")]
        Europe_Vaduz,
        [RenderValue("'Europe/Vatican'")]
        Europe_Vatican,
        [RenderValue("'Europe/Vienna'")]
        Europe_Vienna,
        [RenderValue("'Europe/Vilnius'")]
        Europe_Vilnius,
        [RenderValue("'Europe/Volgograd'")]
        Europe_Volgograd,
        [RenderValue("'Europe/Warsaw'")]
        Europe_Warsaw,
        [RenderValue("'Europe/Zagreb'")]
        Europe_Zagreb,
        [RenderValue("'Europe/Zaporozhye'")]
        Europe_Zaporozhye,
        [RenderValue("'Europe/Zurich'")]
        Europe_Zurich,


        // India
        [RenderValue("'Indian/Antananarivo'")]
        Indian_Antananarivo,
        [RenderValue("'Indian/Chagos'")]
        Indian_Chagos,
        [RenderValue("'Indian/Christmas'")]
        Indian_Christmas,
        [RenderValue("'Indian/Cocos'")]
        Indian_Cocos,
        [RenderValue("'Indian/Comoro'")]
        Indian_Comoro,
        [RenderValue("'Indian/Kerguelen'")]
        Indian_Kerguelen,
        [RenderValue("'Indian/Mahe'")]
        Indian_Mahe,
        [RenderValue("'Indian/Maldives'")]
        Indian_Maldives,
        [RenderValue("'Indian/Mauritius'")]
        Indian_Mauritius,
        [RenderValue("'Indian/Mayotte'")]
        Indian_Mayotte,
        [RenderValue("'Indian/Reunion'")]
        Indian_Reunion,


        // Pacific
        [RenderValue("'Pacific/Apia'")]
        Pacific_Apia,
        [RenderValue("'Pacific/Auckland'")]
        Pacific_Auckland,
        [RenderValue("'Pacific/Chatham'")]
        Pacific_Chatham,
        [RenderValue("'Pacific/Chuuk'")]
        Pacific_Chuuk,
        [RenderValue("'Pacific/Easter'")]
        Pacific_Easter,
        [RenderValue("'Pacific/Efate'")]
        Pacific_Efate,
        [RenderValue("'Pacific/Enderbury'")]
        Pacific_Enderbury,
        [RenderValue("'Pacific/Fakaofo'")]
        Pacific_Fakaofo,
        [RenderValue("'Pacific/Fiji'")]
        Pacific_Fiji,
        [RenderValue("'Pacific/Funafuti'")]
        Pacific_Funafuti,
        [RenderValue("'Pacific/Galapagos'")]
        Pacific_Galapagos,
        [RenderValue("'Pacific/Gambier'")]
        Pacific_Gambier,
        [RenderValue("'Pacific/Guadalcanal'")]
        Pacific_Guadalcanal,
        [RenderValue("'Pacific/Guam'")]
        Pacific_Guam,
        [RenderValue("'Pacific/Honolulu'")]
        Pacific_Honolulu,
        [RenderValue("'Pacific/Johnston'")]
        Pacific_Johnston,
        [RenderValue("'Pacific/Kiritimati'")]
        Pacific_Kiritimati,
        [RenderValue("'Pacific/Kosrae'")]
        Pacific_Kosrae,
        [RenderValue("'Pacific/Kwajalein'")]
        Pacific_Kwajalein,
        [RenderValue("'Pacific/Majuro'")]
        Pacific_Majuro,
        [RenderValue("'Pacific/Marquesas'")]
        Pacific_Marquesas,
        [RenderValue("'Pacific/Midway'")]
        Pacific_Midway,
        [RenderValue("'Pacific/Nauru'")]
        Pacific_Nauru,
        [RenderValue("'Pacific/Niue'")]
        Pacific_Niue,
        [RenderValue("'Pacific/Norfolk'")]
        Pacific_Norfolk,
        [RenderValue("'Pacific/Noumea'")]
        Pacific_Noumea,
        [RenderValue("'Pacific/Pago_Pago'")]
        Pacific_Pago_Pago,
        [RenderValue("'Pacific/Palau'")]
        Pacific_Palau,
        [RenderValue("'Pacific/Pitcairn'")]
        Pacific_Pitcairn,
        [RenderValue("'Pacific/Pohnpei'")]
        Pacific_Pohnpei,
        [RenderValue("'Pacific/Ponape'")]
        Pacific_Ponape,
        [RenderValue("'Pacific/Port_Moresby'")]
        Pacific_Port_Moresby,
        [RenderValue("'Pacific/Rarotonga'")]
        Pacific_Rarotonga,
        [RenderValue("'Pacific/Saipan'")]
        Pacific_Saipan,
        [RenderValue("'Pacific/Samoa'")]
        Pacific_Samoa,
        [RenderValue("'Pacific/Tahiti'")]
        Pacific_Tahiti,
        [RenderValue("'Pacific/Tarawa'")]
        Pacific_Tarawa,
        [RenderValue("'Pacific/Tongatapu'")]
        Pacific_Tongatapu,
        [RenderValue("'Pacific/Truk'")]
        Pacific_Truk,
        [RenderValue("'Pacific/Wake'")]
        Pacific_Wake,
        [RenderValue("'Pacific/Wallis'")]
        Pacific_Wallis,
        [RenderValue("'Pacific/Yap'")]
        Pacific_Yap,



        // Other
        [RenderValue("'Etc/GMT+3'")]
        Etc_GMTPLUS3,
        [RenderValue("'Etc/GMT+4'")]
        Etc_GMTPLUS4,
        [RenderValue("'Etc/GMT+5'")]
        Etc_GMTPLUS5,
        [RenderValue("'Etc/GMT+6'")]
        Etc_GMTPLUS6,
        [RenderValue("'Etc/GMT+7'")]
        Etc_GMTPLUS7,
        [RenderValue("'Etc/GMT+8'")]
        Etc_GMTPLUS8,
        [RenderValue("'Etc/GMT+9'")]
        Etc_GMTPLUS9,
        [RenderValue("'Etc/GMT-0'")]
        Etc_GMT_0,
        [RenderValue("'Etc/GMT-1'")]
        Etc_GMT_1,
        [RenderValue("'Etc/GMT-10'")]
        Etc_GMT_10,
        [RenderValue("'Etc/GMT-11'")]
        Etc_GMT_11,
        [RenderValue("'Etc/GMT-12'")]
        Etc_GMT_12,
        [RenderValue("'Etc/GMT-13'")]
        Etc_GMT_13,
        [RenderValue("'Etc/GMT-14'")]
        Etc_GMT_14,
        [RenderValue("'Etc/GMT-2'")]
        Etc_GMT_2,
        [RenderValue("'Etc/GMT-3'")]
        Etc_GMT_3,
        [RenderValue("'Etc/GMT-4'")]
        Etc_GMT_4,
        [RenderValue("'Etc/GMT-5'")]
        Etc_GMT_5,
        [RenderValue("'Etc/GMT-6'")]
        Etc_GMT_6,
        [RenderValue("'Etc/GMT-7'")]
        Etc_GMT_7,
        [RenderValue("'Etc/GMT-8'")]
        Etc_GMT_8,
        [RenderValue("'Etc/GMT-9'")]
        Etc_GMT_9,
        [RenderValue("'Etc/GMT0'")]
        Etc_GMT0,
        [RenderValue("'Etc/Greenwich'")]
        Etc_Greenwich,
        [RenderValue("'Etc/UCT'")]
        Etc_UCT,
        [RenderValue("'Etc/Universal'")]
        Etc_Universal,
        [RenderValue("'Etc/UTC'")]
        Etc_UTC,
        [RenderValue("'Etc/Zulu'")]
        Etc_Zulu,
        [RenderValue("'Factory'")]
        Factory,
        [RenderValue("'GB'")]
        GB,
        [RenderValue("'GB-Eire'")]
        GB_Eire,
        [RenderValue("'GMT'")]
        GMT,
        [RenderValue("'GMT+0'")]
        GMTPLUS0,
        [RenderValue("'GMT-0'")]
        GMT_0,
        [RenderValue("'GMT0'")]
        GMT0,
        [RenderValue("'Greenwich'")]
        Greenwich,
        [RenderValue("'Hongkong'")]
        Hongkong,
        [RenderValue("'HST'")]
        HST,
        [RenderValue("'Iceland'")]
        Iceland,
        [RenderValue("'Iran'")]
        Iran,
        [RenderValue("'Israel'")]
        Israel,
        [RenderValue("'Jamaica'")]
        Jamaica,
        [RenderValue("'Japan'")]
        Japan,
        [RenderValue("'Kwajalein'")]
        Kwajalein,
        [RenderValue("'Libya'")]
        Libya,
        [RenderValue("'MET'")]
        MET,
        [RenderValue("'Mexico/BajaNorte'")]
        Mexico_BajaNorte,
        [RenderValue("'Mexico/BajaSur'")]
        Mexico_BajaSur,
        [RenderValue("'Mexico/General'")]
        Mexico_General,
        [RenderValue("'MST'")]
        MST,
        [RenderValue("'MST7MDT'")]
        MST7MDT,
        [RenderValue("'Navajo'")]
        Navajo,
        [RenderValue("'NZ'")]
        NZ,
        [RenderValue("'NZ-CHAT'")]
        NZ_CHAT,
        [RenderValue("'Poland'")]
        Poland,
        [RenderValue("'Portugal'")]
        Portugal,
        [RenderValue("'PRC'")]
        PRC,
        [RenderValue("'PST8PDT'")]
        PST8PDT,
        [RenderValue("'ROC'")]
        ROC,
        [RenderValue("'ROK'")]
        ROK,
        [RenderValue("'Singapore'")]
        Singapore,
        [RenderValue("'Turkey'")]
        Turkey,
        [RenderValue("'UCT'")]
        UCT,
        [RenderValue("'Universal'")]
        Universal,
        [RenderValue("'US/Alaska'")]
        US_Alaska,
        [RenderValue("'US/Aleutian'")]
        US_Aleutian,
        [RenderValue("'US/Arizona'")]
        US_Arizona,
        [RenderValue("'US/Central'")]
        US_Central,
        [RenderValue("'US/East-Indiana'")]
        US_East_Indiana,
        [RenderValue("'US/Eastern'")]
        US_Eastern,
        [RenderValue("'US/Hawaii'")]
        US_Hawaii,
        [RenderValue("'US/Indiana-Starke'")]
        US_Indiana_Starke,
        [RenderValue("'US/Michigan'")]
        US_Michigan,
        [RenderValue("'US/Mountain'")]
        US_Mountain,
        [RenderValue("'US/Pacific'")]
        US_Pacific,
        [RenderValue("'US/Pacific-New'")]
        US_Pacific_New,
        [RenderValue("'US/Samoa'")]
        US_Samoa,
        [RenderValue("'UTC'")]
        UTC,
        [RenderValue("'W-SU'")]
        W_SU,
        [RenderValue("'WET'")]
        WET,
        [RenderValue("'Zulu'")]
        Zulu,
    }
}
