<?php
/*
Generated by CS2PHP
*/
namespace E04_Graphics;
class DynamicImage {
    const HEIGHT = 100;
    const WIDTH = 256;
    public static function PhpMain() {
        global $_GET;
        $compression = filter_input(INPUT_GET, 'compression', FILTER_VALIDATE_INT, array('options' => array('default' => 90), 'flags' => FILTER_FLAG_ALLOW_HEX));
        if (array_key_exists('format', $_GET) && $_GET['format'] == 'jpg')
            self::CreateImage(true, $compression);
        else
            self::CreateImage(false, $compression);
    }
    private static function CreateImage($jpg, $compression) {
        if ($compression < 0)
            $compression = 0;
        else if ($compression > 100)
            $compression = 100;
        if ($jpg)
            header('Content-Type: image/jpg');
        else
            header('Content-Type: image/png');
        $myImage = imagecreatetruecolor(self::WIDTH, self::HEIGHT);
        if (false !== $myImage)
            {
                $color = imagecolorallocate($myImage, 255, 0, 0);
                for($i = 0; $i < self::WIDTH; $i++)
                    {
                        $color = imagecolorallocate($myImage, $i, 255 - $i, 0);
                        if (false !== $color)
                            imageline($myImage, 0, self::HEIGHT - 1, $i, 0, $color);
                        $color = imagecolorallocate($myImage, $i, 0, 255 - $i);
                        if (false !== $color)
                            imageline($myImage, self::WIDTH - 1, 0, self::WIDTH - 1 - $i, self::HEIGHT - 1, $color);
                    }
                $color = imagecolorallocate($myImage, 0, 0, 255);
                imagestring($myImage, 4, 10, 30, 'Hello', $color);
                $color = imagecolorallocate($myImage, 255, 255, 255);
                imagestring($myImage, 4, 10, 50, 'C# to PHP is fantastic', $color);
                if ($jpg)
                    imagejpeg($myImage, null, $compression);
                else
                    imagepng($myImage);
                imagedestroy($myImage);
            }
    }
}
DynamicImage::PhpMain();
?>