<?php
/*
Generated by CS2PHP
*/
namespace E04_Graphics;
class IndexPage {
    public static function PhpMain() {
        echo '<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">' . PHP_EOL;
        echo '<html><head><title>Dynamic image</title></head><body>';
        $examples = array(-1, 10, 50, 100);
        foreach($examples as $i)
            {
                $type = $i < 0 ? 'png' : 'jpg';
                if ($i < 0)
                    echo '<p>PNG</p>';
                else
                    echo '<p>JPG, compression ' . $i . '</p>';
                echo "\r\n<p><img src=\"image.php?format=" . $type . ($i > 0 ? '&compression=' . $i : '') . '" alt="Demo ' . ($i > 0 ? 'jpg' : 'png') . ' image" /></p>' . PHP_EOL;
            }
        echo '</body>' . PHP_EOL;
        echo '</html>' . PHP_EOL;
    }
}
IndexPage::PhpMain();
?>