<?php
/*
Generated by CS2PHP
*/
namespace E04_Graphics;
class IndexPage {
    public static function PhpMain() {
        header('Content-Type: image/png');
        $myImage = imagecreate(200, 100);
        if (false !== $myImage)
            {
                $color = imagecolorallocate($myImage, 0, 0, 0);
                $color = imagecolorallocate($myImage, 255, 0, 0);
                imagestring($myImage, 2, 10, 10, 'Hello', $color);
                imagepng($myImage);
            }
    }
}
IndexPage::PhpMain();
?>