<?php
/*
Generated by CS2PHP
*/
namespace Lang\Php\Examples\BasicFeaturesExample;
require_once('class.complex-number.php');
class ComplexNumberTest {
    public static function PhpMain() {
        $a = new ComplexNumber(3, 2);
        $b = ComplexNumber::op_Implicit(12);
        $c = ComplexNumber::mul1($a, $b);
        $d = ComplexNumber::plus($a, $b);
        $e = ComplexNumber::mul2(ComplexNumber::plus($a, ComplexNumber::op_Implicit(17)), 3);
        $m1 = ComplexNumber::mul1(new ComplexNumber(3, 2), new ComplexNumber(4, 5));
        $m2 = ComplexNumber::mul2(new ComplexNumber(3, 2), 5);
    }
}
ComplexNumberTest::PhpMain();
?>