<?php
/*
Generated by CS2PHP
*/
namespace Lang\Php\Examples\BasicFeaturesExample;
class SwichCaseTest {
    public static function PhpMain() {
        $a = 2 * 3;
        switch ($a) {
            1:
            2:
            3:
                echo 'Something wrong';
                break;
            6:
                echo 'Everything is OK.';
                break;
            default:
                echo 'Something really wrong';
                break;
        }
    }
}
SwichCaseTest::PhpMain();
?>